### ISSUE TITLE
Data sources?

### ISSUE THREAD

**Issue by JMarino5** [null8626/python-weather#18]
I've been finding the temperature data to be inaccurate. 

For example: New York City, NY's temperature (according to python-weather) is 66 degrees Fahrenheit (as of 3:47 PM on March 19th), while python-weather returns:

**61 [CURRENT TEMPERATURE]
2022-03-18 00:00:00 Partly Cloudy 59
2022-03-19 00:00:00 Partly Sunny 56
2022-03-20 00:00:00 Cloudy 51
2022-03-21 00:00:00 Sunny 51
2022-03-22 00:00:00 Mostly Cloudy 47**

As you can see, neither the current temperature nor the entry for today's date (March 19th) match the temperature readout from other sources, let alone each other.

Is this an issue with the data source?

**Comment by vierofernando** [comment]
- When you are accessing the `current` attribute (the forecast for the current day), the API returns a temperature attribute. ([source](https://github.com/vierofernando/python-weather/blob/3bd692b122b03b5e997ad3501f1907fee98b43ab/python_weather/response.py#L86))
- Otherwise, when you are accessing an element of the `forecasts` attribute (an array of forecasts for a few days), The API only returns the lowest and highest temperature. The library rounds up the two ends as the approximate temperature. ([source](https://github.com/vierofernando/python-weather/blob/3bd692b122b03b5e997ad3501f1907fee98b43ab/python_weather/response.py#L36))

**Comment by null8626** [comment]
Issue closed - as it's stale now, and i've switched to a different data source (#25)
